parameters:
#    default.example.class: Poodle\DefaultBundle\Example

services:
#    default.example:
#        class: %default.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
