user_homepage:
    pattern:  /
    defaults: { _controller: UserBundle:Default:index }

user_login:
    pattern:  /login
    defaults: { _controller: UserBundle:User:login }
    
register_login:
    pattern:  /register
    defaults: { _controller: UserBundle:User:register }
    
recover_login:
    pattern:  /recover
    defaults: { _controller: UserBundle:User:recover }